name: Deploy Galactica Service

on:
  workflow_dispatch: 

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run unit-test
        
  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: unit-test
    env:
      DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci
        
      - name: Run Prisma Migrations
        run: npx prisma migrate deploy

      - name: Deploy to dev environment
        run: |
          npm i -g @railway/cli
          railway up --environment ${{ secrets.RAILWAY_DEV_ENVIRONMENT_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}